const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
    console.log('I am ready!');
});

client.on('message', message => {
    if (message.content === 'ping') {
    	message.reply('pong');
  	}
});

client.on('message', message => {
    if (message.content === 'FUCK') {
    	message.reply('WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT
FUCK WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT
FUCK WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT
FUCK WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT

OH, BITCH TRY TO CREEP LIKE IVY
OH, NOW IVY DON’T LIKE ME
CANDLE GONE OUT, IGNITE MY HORNS AGLOW
LET A VET RAP A BULLET THROUGH YOUR BUTTONHOLE
YOU’RE MAKING ME UNCOMFORTABLE
SLUMBER TERROR MY CAVALRY
SANDMAN POINT YOU DOWN TO ME
HESH MADE MAKE THE REST STIFF ATROPHY

FUCK WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT
FUCK WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT
FUCK

ACT ACCORDINGLY, I GOT A QUOTA
HIGH NOON SMOKE RINGS, NO HIGH ROLLERS
BROUGHT YOUR FORECAST AND A SHOVEL
BUBBLES BURIED IN THIS JUNGLE
BUBBLES BURIED IN THIS JUNGLE
BUBBLES BURIED IN THIS JUNGLE
POLAR JUNGLE FROZEN PUNTERS
ALL MY SCULPTURES LOOK SO FLUSTERED
DRESS CODE SWALLOW DICK, GO GET YOUR BOSS
SECURITY TURN GREEN ‘CAUSE I NEVER FLOSS
FUCK EVERYTHING OR I UP THE COST
LACK PEDIGREE, MY INDEX PUSH PAUSE
NOTCH CAN’T TALK, I’M SMEARING MUTE
DON’T HAVE SHIT LOCKED, I HEAR THE PROOF
PETTY FORMULA NEVER AMUSES ME
FUCK IF I EVER LET A BITCH GET USED TO ME

FUCK WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT
FUCK WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT
FUCK WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT
FUCK WEAK, NO RESPECT, NO CHANCE
WICK WICK CEASE AND DESIST WHEN I CHANT
FUCK');
  	}
});

// THIS  MUST  BE  THIS  WAY
client.login(process.env.BOT_TOKEN);
